name: Report a bug
description: Report triton failing to compile a kernel, or giving incorrect results
labels: ["bug"]

body:
- type: markdown
  attributes:
    value: |
      #### Disclaimer
      The core triton team is small and has very limited capacity. We may not have time to look into your report.
      For the best results, please:
        - Read the instructions in README: https://github.com/woct0rdho/triton-windows
        - Use the test script in README to check if Triton itself works, and read the troubleshoot below the test script.
        - Avoid submitting duplicates. Search through [the existing and past issues](https://github.com/triton-lang/triton/issues?q=is%3Aissue+sort%3Acreated-desc+) first to see if it's been reported previously.
        - Check if all your Python packages, including Triton and PyTorch, are upgraded to the latest version.
        - Provide all relevant information in the initial report, to prevent unnecessary back and forth discussion.
        - If you can, try to diagnose and/or fix the issue yourself. We welcome high quality contributions.
- type: textarea
  attributes:
    label: Describe the bug
    description: |
      Please provide a clear and concise description of what the bug is.

      If relevant, add a [minimal complete example](https://stackoverflow.com/help/minimal-reproducible-example) that reproduces the bug.

      If the code is too long (hopefully, it isn't), feel free to put it in a public gist and link it in the issue: https://gist.github.com .

      Please also paste or describe the results you observe instead of the expected results. If you observe an error, please paste the error message including the **full** traceback of the exception. It may be relevant to wrap error messages in ```` ```triple quotes blocks``` ````.
    placeholder: |
      A clear and concise description of what the bug is.

      ```python
      # Sample code to reproduce the problem
      ```

      ```
      The error message you got, with the full traceback.
      ```
  validations:
    required: true
- type: textarea
  attributes:
    label: Environment details
    description: |
      Please include any relevant context, including what GPU you are using, the versions of Python, PyTorch, Triton, and other relevant packages.
    placeholder: |
        GPU: ...
        Python: ...
        PyTorch: ...
        Triton: ...
  validations:
    required: true
