# This workflow does not clean caches before building,
# so the wheel may contain __pycache__ or files from another branch

name: Build and Test Triton

on:
  workflow_dispatch:
    inputs:
      git_tag:
        description: Git tag
        required: true
        type: string
        default: main-windows
      python_minor:
        description: Python minor version
        required: true
        type: string
        default: '12'
      pytest_args:
        description: pytest args
        required: true
        type: string
        default: '-n 0 -s --tb=short'

jobs:
  build-and-test-triton:
    runs-on: windows-a10
    steps:
      - name: Create venv
        shell: powershell
        run: |
          pip install --upgrade uv
          uv venv .venv-cp3${{ inputs.python_minor }} --python 3.${{ inputs.python_minor }}
          .venv-cp3${{ inputs.python_minor }}\Scripts\activate.ps1
          python -m ensurepip --upgrade
          python -m pip install --upgrade pip

      - uses: ilammy/msvc-dev-cmd@v1

      - name: Build wheel
        shell: powershell
        run: |
          # Get-ChildItem Env:
          # (Get-WmiObject Win32_Processor).Name
          # (Get-WmiObject Win32_PhysicalMemory | Measure-Object -Property Capacity -Sum).Sum / 1GB
          # (Get-WmiObject Win32_VideoController).Name

          .venv-cp3${{ inputs.python_minor }}\Scripts\activate.ps1
          # Get-Command -All python
          # python --version
          python -m pip install --upgrade cibuildwheel

          git config --global core.autocrlf false
          if (Test-Path -Path triton-windows)
          {
            cd triton-windows
            git add .
            git reset --hard HEAD
            git fetch origin ${{ inputs.git_tag }} --depth 1
            git checkout FETCH_HEAD -B ${{ inputs.git_tag }}
          }
          else
          {
            git clone --branch ${{ inputs.git_tag }} --depth 1 https://github.com/woct0rdho/triton-windows.git
            cd triton-windows
          }
          git rev-parse HEAD

          $Env:TRITON_BUILD_BINARY = "0"
          $Env:TRITON_BUILD_PROTON = "0"
          $Env:TRITON_BUILD_UT = "0"
          $Env:CIBW_BUILD = "{cp3${{ inputs.python_minor }}-win_amd64,}"
          $Env:CIBW_BUILD_VERBOSITY = "1"
          $Env:CIBW_ENABLE = "cpython-freethreading"
          rm wheelhouse/*
          if (Test-Path -Path setup.py)
          {
            cibuildwheel .
          }
          else
          {
            cibuildwheel python
          }

      - uses: actions/upload-artifact@v4
        with:
          path: triton-windows/wheelhouse/*

      - name: Unit test
        shell: powershell
        run: |
          .venv-cp3${{ inputs.python_minor }}\Scripts\activate.ps1
          python -m pip install --upgrade numpy pytest-xdist scipy
          python -m pip install --pre --upgrade 'torch<2.8' --index-url https://download.pytorch.org/whl/nightly/cu128
          cd triton-windows/wheelhouse
          python -m pip install $(Get-ChildItem | Select-Object -First 1)
          rm -r ~/.triton/cache
          cd ../python/test/unit
          pytest ${{ inputs.pytest_args }}
